### PR TITLE
Add proposal stage

### PR DESCRIPTION
**Pull request by whitneyit**
As discussed in #29, this updates the `README.md` with which stage of the [tc39](https://github.com/tc39/ecma262) proposal process this is in.

### CODE REVIEW

**Comment by vitorbal** [comment]
Should be stage 2 now 🎉

**Comment by acusti** [comment]
Should also update the metadata in https://github.com/jeffmo/es-class-public-fields/blob/master/spec/index.htm#L8.

And I’m not clear how the gh-pages content is generated, but that also needs an update (`<h1 class="version">Stage 1 Draft / July 26, 2016</h1>` in [gh-pages/index.html#L6](https://github.com/jeffmo/es-class-public-fields/blob/gh-pages/index.htm#L6))

And lastly, undoubtedly outside the scope of this PR, the repo description needs to be updated to say “Stage 2”.

Oh joy! 🚀  😂

**Comment by ljharb** [comment]
The gh-pages is generated from the file in master using `ecmarkdown`.

**Comment by whitneyit** [comment]
I just noticed that this slipped through the cracks. The above changes have now been completed. Also, the https://tc39.github.io/proposal-class-public-fields/ document still says stage 1

> Stage 1 Draft / July 26, 2016

**Comment by jeffmo** [comment]
Thanks for sending this over (forever ago...sorry about that!).

**Comment by whitneyit** [comment]
No problems buddy

**Pull request merged**
